#!/bin/bash
# *********************************************************************************************
# *********************************************************************************************
#
# Install Airwave software packages held on Github
#
# *********************************************************************************************
# *********************************************************************************************

# Set up server name
SERVER=`hostname`

# Set up directories
ROOT=/home/airwave/install
SOURCE=$ROOT/Airwave
INSTALL=/home/airwave/bin

# Make sure we are in the installation root and remove 
cd $ROOT

# Remove the last download if it is hanging about and the last package installation tree
rm master.zip
rm -r Aiwave

# Download the latest package, unzip it and rename
wget https://github.com/basilfisk/Airwave/archive/master.zip
unzip master.zip
mv Airwave-master Airwave

if [ "$SERVER" == "distro" ]; then
	
	# If the root directory does not exist, build the directory tree
	if [ ! -d $INSTALL ]; then mkdir $INSTALL; fi
	if [ ! -d $INSTALL/etc ]; then mkdir $INSTALL/etc; fi
	if [ ! -d $INSTALL/mods ]; then mkdir $INSTALL/mods; fi
	
	# Install the configuration file
	cp $SOURCE/etc/servers/airwave.conf $INSTALL/etc
	
	# Install the scripts
	cp $SOURCE/bin/distro/cdsd $INSTALL
	cp $SOURCE/bin/distro/cdsd.pl $INSTALL
	cp $SOURCE/bin/distro/cds.pl $INSTALL
	cp $SOURCE/bin/distro/encrypt.pl $INSTALL
	cp $SOURCE/bin/menu.pl $INSTALL
	cp $SOURCE/bin/monitor.pl $INSTALL
	
	# Install the Perl modules
	cp $SOURCE/modules/servers/API.pm $INSTALL/mods
	cp $SOURCE/modules/servers/Common.pm $INSTALL/mods
	cp $SOURCE/modules/servers/TK.pm $INSTALL/mods
	
	# Change ownership and permissions
	chown airwave:airwave -R $INSTALL
	chmod 755 $INSTALL/*.pl
	chmod 755 $INSTALL/cdsd
	chmod 644 $INSTALL/etc/*
	chmod 644 $INSTALL/mods/*
fi

if [ "$SERVER" == "prep" ]; then
	# If the root directory does not exist, build the directory tree
	if [ ! -d $INSTALL ]; then
		mkdir $INSTALL
		mkdir $INSTALL/etc
		mkdir $INSTALL/mods
	fi
	
	# Install the configuration files
	cp $SOURCE/admin/crontab.prep $INSTALL/etc
	cp $SOURCE/etc/servers/* $INSTALL/etc
	
	# Install the scripts
	cp $SOURCE/bin/prep/* $INSTALL
	cp $SOURCE/bin/menu.pl $INSTALL
	cp $SOURCE/bin/monitor.pl $INSTALL
	
	# Install the Perl modules
	cp $SOURCE/modules/servers/*.pm $INSTALL/mods
	
	# Change ownership and permissions
	chown airwave:airwave -R $INSTALL
	chmod 755 $INSTALL/*.pl
	chmod 755 $INSTALL/sync*
	chmod 644 $INSTALL/etc/*
	chmod 644 $INSTALL/mods/*.pm
fi
